services:
  winzcart-api:
    image: winzcart-api
    build:
      context: .
      dockerfile: Dockerfile
    container_name: winzcart-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db47070.public.databaseasp.net; Database=db47070; User Id=db47070; Password=oB?38qA@D2+w; Encrypt=True; TrustServerCertificate=True; MultipleActiveResultSets=True;
      - JwtSettings__SecretKey=super_secret_key_that_is_at_least_32_characters_long_for_hmacsha256_winzcart!
      - JwtSettings__Issuer=winzcart-api
      - JwtSettings__Audience=winzcart-clients
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - winzcart-network

networks:
  winzcart-network:
    driver: bridge
